#!/bin/bash

sed -i $HOME/.gitolite.rc -e 's:#[ \t]*LOCAL_CODE[ \t]*=>[ \t]*"$ENV{HOME}/local":LOCAL_CODE => "$ENV{HOME}/local":g'       

mkdir -p $HOME/local/hooks/common
cp hooks/* $HOME/local/hooks/common/
chmod 700 $HOME/local/hooks/common/*
$HOME/bin/gitolite setup

