#!/bin/bash

sed -i $HOME/.gitolite.rc -e 's:#[ \t]*LOCAL_CODE[ \t]*=>[ \t]*"$ENV{HOME}/local":LOCAL_CODE => "$ENV{HOME}/local":g'       

mkdir -p $HOME/local/hooks/common
cp hooks/* $HOME/local/hooks/common/
chmod 700 $HOME/local/hooks/common/*

openssl rand -base64 15 > $HOME/.id_rsa.pass
if [ -f defaults/id_rsa -o -f defaults/id_rsa.pub ]; then
   rm -f defaults/id_rsa defaults/id_rsa.pub
fi
ssh-keygen -b 4096 -t rsa -f defaults/id_rsa -N $(cat $HOME/.id_rsa.pass)
ssh-keygen -f defaults/id_rsa.pub -e -m pem | openssl rsa -RSAPublicKey_in -pubout > defaults/id_rsa.pem
git add defaults/id_rsa defaults/id_rsa.pub defaults/id_rsa.pem
git commit -m "added deployment rsa key" defaults/id_rsa defaults/id_rsa.pub defaults/id_rsa.pem && git push

cd $HOME
bin/gitolite setup

 