#!/bin/bash

export DEPLOY_ALLOWED_BRANCH=online
export DEPLOY_ROOT="$HOME/work"

while read oldrev newrev refname
do

    export DEPLOY_BRANCH=$(git rev-parse --symbolic --abbrev-ref $refname)
    export DEPLOY_OLDREV="$oldrev"
    export DEPLOY_NEWREV="$newrev"
    export DEPLOY_REFNAME="$refname"
    export GIT_DIR="$(cd $(dirname $(dirname $0));pwd)"
    export DEPLOY_REPONAME="$(basename ${GIT_DIR})"
    export DEPLOY_NAME="${DEPLOY_REPONAME%.git}"

    if [ ! -z "${DEPLOY_ALLOWED_BRANCH}" ]; then
        if [ "${DEPLOY_ALLOWED_BRANCH}" != "$DEPLOY_BRANCH" -a "$DEPLOY_NAME" != "keepmywork" ]; then
            echo "githook: Branch '$DEPLOY_BRANCH' of '${DEPLOY_APP_NAME}' docker will not be deployed. Exiting."
            exit 0
        fi
    fi
    
    echo "general deployment hook is activated"

    export GIT_WORK_TREE="${DEPLOY_ROOT}/${DEPLOY_REPONAME}"
    mkdir -p "${GIT_WORK_TREE}"

    git checkout -f "${DEPLOY_BRANCH}" || exit 1
    git reset --hard "$DEPLOY_NEWREV" || exit 1
    
    cd $GIT_WORK_TREE
    export MAKE_DEFAULTS=$DEPLOY_ROOT/keepmywork.git/defaults
    if [ -f shutdown.txt ] && [[ $(head -n1 shutdown.txt) == *"yes"* ]]; then
	echo "githook: Docker shutdown requested"
	make down
    else
        make up
    fi

done

